### ISSUE TITLE
External web font dependencies prevent loading in certain countries

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#123]
Web fonts hosted on https://fonts.googleapis.com/ prevent the web app from loading where Google services are blocked (China). 

We should include these fonts with builds presuming the license allows for this.

**Comment by guylepage3** [comment]
We can add the fonts in directly to the app. I'll add this issue to the build milestone.

**Comment by shea256** [comment]
@guylepage3 @larrysalibra Moving this to v0.3 so we can take care of it for the next release.

**Comment by larrysalibra** [comment]
Done.
