### ISSUE TITLE
Make 3rd party URLs customizable (e.g. for PGP keys)

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-portal#137]
The browser uses some hardcoded urls for link to further information (i.e. the actual [PGP key](https://github.com/blockstack/blockstack-browser/blob/85d0a0026862350872a13a1e68db83c1ab47df42/app/js/utils/account-utils.js#L102)).
Since these urls aren't that fixed as these above (like Twitter and co.), it would be cool to customize these in a settings tab.

In this example: Setting an own keyserver instead of using the hardcoded "pgp.mit.edu".

Thanks,
Valentin

**Comment by shea256** [comment]
Yes good call @vsund. I'm actually thinking we could have an overlay that displays the PGP key in the app itself. The PGP key can be loaded directly, unlike with other proofs.

**Comment by shea256** [comment]
Larry: This also applies to UTXOs.

**Comment by larrysalibra** [comment]
> @larrysalibra: "This also applies to URLs to UTXOs."

URLs for UTXOs are configurable as of the completion of #171.

**Comment by larrysalibra** [comment]
Besides PGP keyserver as @vsund mentions, we are also hardcoding block explorers for bitcoin and ethereum addresses:

```
'pgp': {
    label: 'PGP', iconClass: 'fa-key', social: false,
    urlTemplate: 'https://pgp.mit.edu/pks/lookup?search={identifier}&op=vindex&fingerprint=on'
  },
  'bitcoin': {
    label: 'Bitcoin', iconClass: 'fa-bitcoin', social: false,
    urlTemplate: 'https://www.blocktrail.com/BTC/address/{identifier}'
  },
  'ethereum': {
    label: 'Ethereum', iconClass: 'fa-key', social: false,
    urlTemplate: 'https://tradeblock.com/ethereum/account/{identifier}'
  }
```

I'm going to make all 3 configurable and we can open another issue to load the key directly with an overlay as @shea256 suggests above at a future date (since that requires some design work)

**Comment by larrysalibra** [comment]
Bitcoin explorer, Ethereum explorer and PGP keyserver URLs are now user configurable in the account settings page.

I also changed the default Bitcoin explorer to our own Blockstack Explorer. 🤠

https://github.com/blockstack/blockstack-portal/commit/c57e8bca07ccfcc00ce2363c90ce16a1641f739e

**Comment by larrysalibra** [comment]
See #250 for the issue about loading the PGP directly in the Portal. 

Thank you again @vsund for the great feedback! Apologies for taking 3 months to deliver!

Closing this issue.
