### ISSUE TITLE
Error text is white on white background

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-portal#138]
When getting an error while searching things (for example `No results found`), it gets displayed as white text on a white background.

Thanks,
Valentin

**Comment by shea256** [comment]
@vsund Can you please check to see if you're still getting this error? And if so can you screenshot it?

@guylepage3 do you know if this was taken care of?

**Comment by vsund** [comment]
Yeah, using the `master` branch and `npm run dev` I got this page when browsing http://localhost:3000/search/asdf321:

![blockstack-browser](https://cloud.githubusercontent.com/assets/10466835/22187035/94a02668-e0ff-11e6-997c-a30198ef036b.png)

---
But that's probably more helpful when I highlight everything on the page :D
![blockstack-browser-highlighted](https://cloud.githubusercontent.com/assets/10466835/22187036/980029fc-e0ff-11e6-956a-3d8873066bf9.png)

**Comment by guylepage3** [comment]
@shea256 i have not addressed this yet. I'll look into it now.

**Comment by shea256** [comment]
@guylepage3: "This is no longer relevant."

Closing.

**Comment by vsund** [comment]
The the new release has this problem (still/again?). I pulled from the `master` branch.

**Comment by guylepage3** [comment]
@vsund where is this appearing? I am unable to recreate it. Can you provide me with a bit more info? thanks.

**Comment by vsund** [comment]
http://localhost:3000/profiles/search/asdf123 (for example) throws a `No results found`. I can add a screenshot if you like, but I think it wouldn't add much value :)

**Comment by guylepage3** [comment]
@vsund are you sure you have the latest version of the portal? I am not getting that error. Here's what I am getting..

<img width="1250" alt="screenshot 2017-03-17 10 42 45" src="https://cloud.githubusercontent.com/assets/1711854/24048204/7a1335d2-0afe-11e7-9c88-cca894d1e241.png">

**Comment by vsund** [comment]
I'm on the latest revision of `master` (Ryan's commit `f97fd6ff`). I looked at the branch overview page, it seems that `ui-0.4` isn't merged yet, maybe that's the problem?
Which branch do you use / which one is the latest?

**Comment by shea256** [comment]
@vsund We're working on branches `v0.5` and `ui-v0.5` right now. Those two haven't been merged yet.

**Comment by vsund** [comment]
Ah, then I think it can remain closed ;)

And I just noticed that there's http://localhost:3000/profiles/search/asdf123 and http://localhost:3000/profiles/i/search/asdf123. The first one gives me @guylepage3's view, the second one the old view (the old one is linked in the "Profile" app).

**Comment by guylepage3** [comment]
Cool @vsund. Let's keep this one closed. 😄
