### ISSUE TITLE
Create official dropbox app & add branding

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#142]
I've created a Blockstack Dropbox app for development as part of self hosting support on Dropbox.  It's limited to the first 500 people that connect their Blockstack browser to it. We'll need to apply for production access either with this app or another add branding assets.

<img width="1150" alt="screen shot 2016-12-27 at 10 02 42 pm" src="https://cloud.githubusercontent.com/assets/597182/21501160/635cda1c-cc80-11e6-8638-d1e903a65b35.png">
<img width="834" alt="screen shot 2016-12-27 at 10 02 54 pm" src="https://cloud.githubusercontent.com/assets/597182/21501161/687aab82-cc80-11e6-968e-3b417c544ea3.png">

**Comment by shea256** [comment]
@larrysalibra OK sounds good. I can create a new app if you'd like and apply.

Also moving this issue to the v0.3 milestone.

**Comment by guylepage3** [comment]
@shea256:

> We should also change the redirect URL from "/account/settings" to "/".

**Comment by larrysalibra** [comment]
You should also be redirected to where you start.

**Comment by larrysalibra** [comment]
I've added branding to our Dropbox App. It won't be considered for production until we have at least 50 users (we only have 10 so far).

As part of the application for production, we need to point the Dropbox review personal to our website with the app users will download.

@guylepage3 @shea256 I suggest we create a download page on https://blockstack.org and link to the latest version of the Browser Portal. Thoughts?

**Comment by larrysalibra** [comment]
We can also use the Dropbox App as the "official" app...no need to create a new one. We can transfer it to another account at any time - just need to submit a support ticket.
