### ISSUE TITLE
Fix & enable test suite.

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#161]
The browser's test suite is broken. We should also add a lot of coverage especially for crypto-related things: verifying tokens, bitcoin wallet, etc

**Comment by shea256** [comment]
Great call @larrysalibra. Good thing to add in to v0.4.

**Comment by larrysalibra** [comment]
We don't need to add lots of coverage for this issue, we just need to make sure that the project is set up so that:
1. It is easy for us to add test cases going forward
2. Test cases get run by the CI server on commit

**Comment by shea256** [comment]
@larrysalibra Good call. I like the idea of starting very small in terms of the amount of test coverage for this sprint. For next sprint we can start expanding on the coverage.

**Comment by larrysalibra** [comment]
Closing this. See #368
