### ISSUE TITLE
Restore account doesn't work

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#166]
Since we've moved to the new no-need-to-register model, restoring account doesn't work.

**Comment by larrysalibra** [comment]
This is because a page reload causes a new account to be generated because of these lines is `App.js`

```
  componentWillMount() {
    this.props.initializeWallet("password", null)
  }
```

Commenting them out fixes the problem.

**Comment by guylepage3** [comment]
@larrysalibra can you apply a Label and Milestone for this issue? Thx

**Comment by larrysalibra** [comment]
I've re-enabled the account restore page and adjusted it to match the new settings style.
