### ISSUE TITLE
adjust layout of profiles app list view (post profiles app object)

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#202]
Adjust layout of profiles app list view as a result of [#230: create a ProfilesApp object that wraps all pages](https://github.com/blockstack/blockstack-portal/issues/230).

**Comment by guylepage3** [comment]
Shoot. @shea256 This is for tomorrow's release?

**Comment by shea256** [comment]
@guylepage3 Yes, it's due Sunday.

We only need to put the logos in the left side right?

**Comment by shea256** [comment]
We're pushing this to 0.4.0

**Comment by guylepage3** [comment]
Pinning [#230: create a ProfilesApp object that wraps all pages](https://github.com/blockstack/blockstack-portal/issues/230) to this issue

**Comment by guylepage3** [comment]
complete
