### ISSUE TITLE
Display errors from blockstack-core registration call

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#209]
`POST /v1/names` returns information about problems that prevent successful registration such as inadequate balance. We need to show these to the user.

example:

<img width="1071" alt="screen shot 2017-02-12 at 4 39 40 pm" src="https://cloud.githubusercontent.com/assets/597182/22863023/f2a6e13c-f141-11e6-9064-3b8757e5f7dd.png">

```JSON
{"error": "Failed to register name: Address 37tbGfinfPk6h4NCpXRQHAQT9cEWWWGW89 does not have enough balance (need 495479, have 450000)."}
```

**Comment by larrysalibra** [comment]
We also need to handle state where registration fails. IE: don't add the name to the list of preregistered names.

**Comment by guylepage3** [comment]
@larrysalibra @shea256 can we push this to [Release v0.4.0](https://github.com/blockstack/blockstack-browser/milestone/4)?

**Comment by shea256** [comment]
Yes let's push this to 0.4.0.

**Comment by shea256** [comment]
@larrysalibra Can you mentioned you could take a few more tasks up. Can you take this one off my hands?

**Comment by larrysalibra** [comment]
Yes.

**Comment by larrysalibra** [comment]
Complete. We can give users more detailed feedback as part of #232.
