### ISSUE TITLE
npm install fail on web-0.3

### ISSUE THREAD

**Issue by cstrangedk** [blockstack/blockstack-portal#215]
This is still happening on `web-0.3`

Ref: #200, #199, #125 

**Steps to reproduce:**

`git clone https://github.com/blockstack/blockstack-browser.git -b web-0.3`
`npm install`

also attempted [#200 (comment)](https://github.com/blockstack/blockstack-browser/issues/200#issuecomment-279243700) but still generates an error.

**Error:**

`npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) Permission denied (publickey).
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git)
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (ssh://git@github.com/shea256/bitcoinjs-lib.git) and the repository exists.`

**Comment by shea256** [comment]
Thanks for reporting @cstrangedk, I'll take a look and get back to you on this.

**Comment by shea256** [comment]
Temporary fix for those running into this issue:

1. Install bitcoinjs-lib from https://github.com/shea256/bitcoinjs-lib
2. Install ecurve from https://github.com/shea256/ecurve
3. Continue with `npm install`

**Comment by larrysalibra** [comment]
`blockstack-keychains` version 0.0.8 no longer requires `ecurve` by `git-ssh`. 

I tested `npm install` of the portal (from branch `v0.4` on a new user account without github ssh credentials and it should work now. Hopefully this is the last time we'll run into this issue, but please re-open if it reoccurs.

Thanks again @cstrangedk for taking the time to report this!
