### ISSUE TITLE
Version APIs & track user url customization

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#229]
Right now users have to click the Reset API button every time we add an api method. 

When we add new api keys, they add the new key with the default URL while not overwriting the user's other possibly customized URLs.

**Comment by shea256** [comment]
This sounds like a nice to have and not strictly necessary for this sprint.

We have a lot on our plate and this will take 2 hours.

Thoughts on whether we should keep this or defer it?

**Comment by larrysalibra** [comment]
Let's push it to the next sprint. It will go nicely with adding update capability to the macOS app (#284). Our user story could be something like "User should be able to easily update Blockstack"

**Comment by shea256** [comment]
Sounds great. Let's actually mark it as "backlog" for now so that 0.6 is pristine and then we can add tasks from scratch on the 20th.

**Comment by larrysalibra** [comment]
Tagged commits with wrong issue number: https://github.com/blockstack/blockstack-portal/commit/c7e5e5718e57030db32f04adcab81f703b339f94 https://github.com/blockstack/blockstack-portal/commit/cce370b1db09f963bcd14c4f0d9cf37494bd62c9

**Comment by larrysalibra** [comment]
Complete
