### ISSUE TITLE
create a ProfilesApp object that wraps all pages

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#230]

**Comment by shea256** [comment]
As you can see, I created a route wrapper for the profiles object:

https://github.com/blockstack/blockstack-portal/blob/8dde7d905fb3cf3d37dac28b59a4a41627775b7c/app/js/routes.js#L38

I also created the ProfilesApp object and included `{this.props.children}` which allows for the inclusion of the children inside the route wrapper:

https://github.com/blockstack/blockstack-portal/blob/8dde7d905fb3cf3d37dac28b59a4a41627775b7c/app/js/pages/profiles/ProfilesApp.js#L47

**Comment by shea256** [comment]
Now, all pages inside of the profiles app are wrapped with the ProfilesApp object header. @guylepage3 you'll see that some of the styling has been broken, and that will need to be fixed.

@larrysalibra This technique can be used as a model for the creation of the Wallet app.

Closing this issue out.
