### ISSUE TITLE
add the ability for the user to restore an account in the welcome modal

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#231]

**Comment by shea256** [comment]
@larrysalibra Think you could take this issue off my hands?

We can implement it similar to how we did it before with a small link at the bottom of the first modal that then takes you to a "restore account" modal view.

We might have screenshots of this somewhere @guylepage3.

**Comment by larrysalibra** [comment]
Sure.

**Comment by shea256** [comment]
Awesome thank you

**Comment by guylepage3** [comment]
Referencing [design launch modal](https://github.com/blockstack/blockstack-browser/issues/214)

**Comment by larrysalibra** [comment]
Done & merged.
