### ISSUE TITLE
add a wallet app and put the deposit and withdraw pages inside

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#241]

**Comment by larrysalibra** [comment]
See https://github.com/blockstack/blockstack-portal/commit/8dde7d905fb3cf3d37dac28b59a4a41627775b7c

**Comment by larrysalibra** [comment]
Completed. @guylepage3 I duplicated the settings app icon as `app-wallet.png` -  we can replace that with the icon when ready.

<img width="1134" alt="screen shot 2017-02-22 at 12 39 46 pm" src="https://cloud.githubusercontent.com/assets/597182/23208026/23ccc512-f8fc-11e6-8f8f-1cd27d450506.png">
