### ISSUE TITLE
design the wallet app

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#242]
see #241 for reference

**Comment by guylepage3** [comment]
@shea256 @larrysalibra will requirements for the wallet be as follows:
- [ ] deposit
- [ ] withdraw
- [ ] backup account
- [ ] restore account
- [ ] delete account

**Comment by shea256** [comment]
@guylepage3 no, only deposit and withdraw

**Comment by shea256** [comment]
The backup, restore, and delete account operations will be accessible in the settings app.

**Comment by larrysalibra** [comment]
<img width="1134" alt="screen shot 2017-02-22 at 12 39 46 pm" src="https://cloud.githubusercontent.com/assets/597182/23208069/4d35f18a-f8fc-11e6-9fa9-8c6cf6f406d9.png">

Added the Wallet App in #241 - as part of the design it will also need an icon.

**Comment by guylepage3** [comment]
Pinning [#241: add a wallet app and put the deposit and withdraw pages inside](https://github.com/blockstack/blockstack-portal/issues/241) to this issue

**Comment by shea256** [comment]
@guylepage3 Can we see the older wallet app designs that we put together?

**Comment by guylepage3** [comment]
definitely.. let me organize them

**Comment by shea256** [comment]
## Requirements

1. A large balance display that appears on all tabs.
1. Three tabs:
    1. `Activity`: list of historical transactions (this will be blank at first)
    1. `Receive`: displays (a) a bitcoin address (b) a QR code.
    1. `Send`: displays (a) a "To" field (b) an "Amount" field (c) a "Password" field

## Related Examples

![download](https://cloud.githubusercontent.com/assets/994646/24313868/1eb7380c-10b5-11e7-9ec9-018c07e68401.jpg)

![download](https://cloud.githubusercontent.com/assets/994646/24313119/0a6b81b2-10b2-11e7-8a4a-6ce7ff488d34.png)

**Comment by guylepage3** [comment]
<img width="880" alt="screenshot 2017-03-24 18 44 04" src="https://cloud.githubusercontent.com/assets/1711854/24316181/6fde3b56-10c2-11e7-875f-bfba83213118.png">
<img width="889" alt="screenshot 2017-03-24 18 44 24" src="https://cloud.githubusercontent.com/assets/1711854/24316182/6fdf81d2-10c2-11e7-96c8-b29f17761d8c.png">
<img width="877" alt="screenshot 2017-03-24 18 47 55" src="https://cloud.githubusercontent.com/assets/1711854/24316183/6fdfcf16-10c2-11e7-881d-fed80f449fb1.png">

**Comment by guylepage3** [comment]
@shea256 @larrysalibra 

Hmm. Question.. Do we want to display the wallet balance in USD or BTC? I've noticed that even Coinbase displays their wallet balance in USD. Seems logical. No?

**Comment by guylepage3** [comment]
Also, will users be able to send btc to Blockstack ID's or to bitcoin addresses only?

**Comment by larrysalibra** [comment]
> Do we want to display the wallet balance in USD or BTC? I've noticed that even Coinbase displays their wallet balance in USD. Seems logical.

Coinbase displays their balance in USD only for US users. If you're a UK user (or other place user) you get you balance in your local currency. To provide a good user experience, we quickly get into questions like: which currency to default to? How does the user change it? How do we choose the default? Geolocation? Browser local settings?

We'd also need to get exchange rate information from a 3rd party API. Which API should we use? Is it free? Can it handle a lot of users? What are the privacy implications for adding that API?

I think for this sprint we should stick to BTC. We can open a ticket to add this feature in the future. My view is that it's not as pressing as our other issues.

> Also, will users be able to send btc to Blockstack ID's or to bitcoin addresses only?

It's trivial to implement sending bitcoin to Blockstack IDs (are we still calling them that?). Let's do it.

**Comment by larrysalibra** [comment]
@guylepage3 

I replied before looking at your mock ups. I really like how it has the USD price under the BTC value.

Maybe we should do this and for now not give the user a choice of fiat currencies. Most people have a good idea what their local currency to USD exchange rate is anyways. @shea256 what do you think?

**Comment by guylepage3** [comment]
>I think for this sprint we should stick to BTC. We can open a ticket to add this feature in the future. My view is that it's not as pressing as our other issues.

@larrysalibra Sorry this is for design so that I can future-proof a little. Design requires a full requirement capture in order to not waste a design and have to throw it out just because we need to add a new feature. We need to get better at this. If Blockstack was a client I would make us go through an entire creative process. That's how you get decent design. But we do not have that luxury. So in order to streamline (somewhat) we need to gather as many requirements as fast as we can so that we don't throw the baby out with the bathwater.

**Comment by guylepage3** [comment]
@shea256 @larrysalibra what are we going to call the wallet? any names that come to mind? or what do you think.. simply "wallet"

**Comment by guylepage3** [comment]
![wallet-desktop-dark-landscape 2x](https://cloud.githubusercontent.com/assets/1711854/24477530/5b4e46b8-14a5-11e7-9896-56b5a964f82b.png)
![wallet-desktop-dark-landscape2 2x](https://cloud.githubusercontent.com/assets/1711854/24477531/5b513936-14a5-11e7-8bcc-951fc77c8545.png)
![wallet-desktop-dark-landscape3 2x](https://cloud.githubusercontent.com/assets/1711854/24477532/5b517202-14a5-11e7-954d-127fb951a239.png)
![wallet-desktop-dark-landscape4 2x](https://cloud.githubusercontent.com/assets/1711854/24477534/5b51d5c6-14a5-11e7-99be-34dba01655fb.png)
![wallet-desktop-dark 2x](https://cloud.githubusercontent.com/assets/1711854/24477533/5b51d148-14a5-11e7-9deb-222ec3132ff0.png)

**Comment by shea256** [comment]
Nice work! Love #2 out of 5!

**Comment by guylepage3** [comment]
#2 has that leather wallet smell. 😂 Lol. It does feel a bit dated to me somehow though. I like the cleanliness of the others personally.

**Comment by shea256** [comment]
The others are harder on my eyes and not as easy for me to navigate.

**Comment by pstan26** [comment]
I like 2 out of 5 too. Didn't realize this was also ryan's pick but it is easier on the eyes and has a friendly green.

**Comment by guylepage3** [comment]
Oh... Naaarrrrrr.... 🙈
