### ISSUE TITLE
apps not breaking on dashboard mobile & tablet view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#244]
Apps are not breaking on mobile & tablet view of the dashboard.

**Comment by guylepage3** [comment]
<img width="788" alt="screenshot 2017-02-20 18 46 34" src="https://cloud.githubusercontent.com/assets/1711854/23145534/fdd1e05a-f79c-11e6-9f6a-8c58444b2e6f.png">
<img width="1191" alt="screenshot 2017-02-20 18 47 00" src="https://cloud.githubusercontent.com/assets/1711854/23145535/fde2c410-f79c-11e6-896c-40de7507a4ae.png">

**Comment by guylepage3** [comment]
Attempting to mimic the scaffolding effect seen on icloud.com. There are 3 media query views that allow for clean and simple viewing on icloud.com. For Portal we will require a 4th mobile view.

<img width="1920" alt="screenshot 2017-02-27 08 14 26" src="https://cloud.githubusercontent.com/assets/1711854/23362749/4179847a-fcc5-11e6-855f-f1e427848723.png">
<img width="1583" alt="screenshot 2017-02-27 08 14 39" src="https://cloud.githubusercontent.com/assets/1711854/23362750/417b4b02-fcc5-11e6-8323-8d4e61ae8fe8.png">
<img width="961" alt="screenshot 2017-02-27 08 14 50" src="https://cloud.githubusercontent.com/assets/1711854/23362751/417c985e-fcc5-11e6-8572-ecf77c6f8acd.png">

**Comment by guylepage3** [comment]
Will be utilizing `flex-wrap` property to execute scaffolding of apps. This will also allow for easy addition of new apps as they appear on the Blockstack Portal Home Screen.

CSS classes and properties checklist to adjust per view.

```
- [ ] `.app-box` { 
}
- [ ] `.app-box img` {
  - [ ] `width`
  - [ ] `box-shadow`
  - [ ] `border-radius` 
}
- [ ] `.app-center` {
}
- [ ] `.app-wrap` {
}
- [ ] `.app-container` {
}
- [ ] `div.app-text-container > h3` {
	- [ ] `font-size`
}

**Comment by guylepage3** [comment]
<img width="331" alt="screenshot 2017-02-27 11 09 29" src="https://cloud.githubusercontent.com/assets/1711854/23368876/5200311e-fcdd-11e6-8f01-a6d88a45d252.png">
<img width="359" alt="screenshot 2017-02-27 11 09 39" src="https://cloud.githubusercontent.com/assets/1711854/23368878/520278b6-fcdd-11e6-87f6-ac41ff943bc3.png">
<img width="490" alt="screenshot 2017-02-27 11 09 50" src="https://cloud.githubusercontent.com/assets/1711854/23368877/5202695c-fcdd-11e6-911e-fa8d94c7450b.png">
<img width="677" alt="screenshot 2017-02-27 11 09 59" src="https://cloud.githubusercontent.com/assets/1711854/23368879/52076812-fcdd-11e6-96e2-534c667229f1.png">

**Comment by shea256** [comment]
Nice @guylepage3!

**Comment by guylepage3** [comment]
Full flex-box wrapping all the from xs–xl device sizes.. 😄 

<img width="494" alt="screenshot 2017-02-27 11 56 33" src="https://cloud.githubusercontent.com/assets/1711854/23370804/dfef8ea6-fce3-11e6-8480-9d5df21e7b0a.png">
<img width="848" alt="screenshot 2017-02-27 11 56 50" src="https://cloud.githubusercontent.com/assets/1711854/23370802/dfeaa698-fce3-11e6-92a4-2f7cf969a566.png">
<img width="1123" alt="screenshot 2017-02-27 11 56 58" src="https://cloud.githubusercontent.com/assets/1711854/23370803/dfebea62-fce3-11e6-97e4-d075079b9dd1.png">

**Comment by guylepage3** [comment]
Complete. Had major issues trying to get the desktop view to be centered vertically but i need to move on. will tackle that in another sprint.

<img width="1007" alt="screenshot 2017-02-28 18 38 04" src="https://cloud.githubusercontent.com/assets/1711854/23439738/2bc30850-fde6-11e6-9b7b-b8d0b3680ca0.png">
<img width="1005" alt="screenshot 2017-02-28 18 38 20" src="https://cloud.githubusercontent.com/assets/1711854/23439736/2bc0fccc-fde6-11e6-84dd-e1c9b9cb80d0.png">
<img width="1005" alt="screenshot 2017-02-28 18 38 34" src="https://cloud.githubusercontent.com/assets/1711854/23439740/2bc53620-fde6-11e6-96ae-7e3c6248d5ea.png">
<img width="1005" alt="screenshot 2017-02-28 18 38 46" src="https://cloud.githubusercontent.com/assets/1711854/23439735/2bc01d7a-fde6-11e6-9b96-6954264a30bb.png">
<img width="1006" alt="screenshot 2017-02-28 18 39 11" src="https://cloud.githubusercontent.com/assets/1711854/23439739/2bc3f6ac-fde6-11e6-9c32-9535b44fbf65.png">
<img width="1247" alt="screenshot 2017-02-28 18 45 22" src="https://cloud.githubusercontent.com/assets/1711854/23439737/2bc150a0-fde6-11e6-8351-1bf6d7620aae.png">
