### ISSUE TITLE
fix required propTypes in Balance object

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#248]
```html
<Balance />
```

<img width="424" alt="screen shot 2017-02-21 at 5 54 18 pm" src="https://cloud.githubusercontent.com/assets/994646/23188983/cb4e0e70-f85e-11e6-8d41-5823cc101f10.png">

![screen shot 2017-02-21 at 5 53 31 pm](https://cloud.githubusercontent.com/assets/994646/23188973/c2885bba-f85e-11e6-9838-befc537c0bcd.png)

**Comment by larrysalibra** [comment]
@shea256 Let me know if this fixes it.

**Comment by larrysalibra** [comment]
Going to close this - please re-open if it is still an issue1
