### ISSUE TITLE
Move fetches out of react components

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#249]
There are a few places we are `fetch`ing state inside react components. This should be moved in the redux store.

**Comment by larrysalibra** [comment]
@shea256 are you working on this? (i see you moved it into doing, but it's still assigned to me)

**Comment by shea256** [comment]
@larrysalibra no that was not intentional.

**Comment by larrysalibra** [comment]
Last remaining fetch is in the PGP overlay react component https://github.com/blockstack/blockstack-portal/commit/592e948bc68fe0d1a034a2874e9e198b147cd7ea

**Comment by larrysalibra** [comment]
Remaining components with fetch:
- [ ] `PGPAccountItem`
- [ ] `AuthModal`
- [ ] `WithdrawPage`

**Comment by larrysalibra** [comment]
Took a bit longer than planned - finally complete!
