### ISSUE TITLE
Create the macOS build for release v0.4

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#264]

**Comment by larrysalibra** [comment]
What are we calling `v0.4`? @guylepage3 @shea256 

Diamond?

**Comment by shea256** [comment]
Do we want to keep this naming scheme or do we want to ditch it?

**Comment by guylepage3** [comment]
i feel like we should ditch it for now. when we have a big release to the public we can name that if we choose. imo

**Comment by shea256** [comment]
Here's what the releases page looks like now:

![screen shot 2017-02-23 at 2 48 04 pm](https://cloud.githubusercontent.com/assets/994646/23276154/40f3c43e-f9d7-11e6-9e5a-54c069e5cc75.png)

**Comment by guylepage3** [comment]
that looks a bit confusing to me.. we need to consolidate our out bound branding. 
```
v0.1-portal
v0.2-portal
v0.3-portal
```
Seems to make more sense. Also is this beta?

**Comment by larrysalibra** [comment]
I also need to decide which commit of blockstack core to include with the build. @jcnelson has continued development on the branch we were building from before `rc-0.14.1b` and the API has changed a bit. He's also fixed some bugs that exist in the version packaged with `v0.4.0` that affect the portal so it makes sense to bump the version.

**Comment by shea256** [comment]
We could say `Portal v0.4` and ditch the colors.

**Comment by larrysalibra** [comment]
Agree w/ @guylepage3 they make more sense for big releases.

**Comment by guylepage3** [comment]
>We could say **Portal v0.4** and ditch the colors.
yeah. or we could just do `v0.4` for simplicity?

**Comment by shea256** [comment]
Yeah @guylepage3 I was suggesting "Portal v0.4" as the name of the release instead of "v0.4-portal".

**Comment by guylepage3** [comment]
yeah. i just think, it's best to keep it simple for developers where we can. was looking here: https://github.com/twbs/bootstrap/releases and it seems so clean and easy to read / understand. 

```
v3.3.6
```
vs.
```
bootstrap v3.3.6
```

**Comment by shea256** [comment]
OK cool just changed the names:

https://github.com/blockstack/blockstack-portal/releases

**Comment by larrysalibra** [comment]
@shea256 @guylepage3 keep me posted over the weekend when you're ready for me to make this build or if you need help on any remaining tasks.

**Comment by guylepage3** [comment]
@larrysalibra will do. I'll be working tomorrow.

**Comment by larrysalibra** [comment]
build uploaded https://github.com/blockstack/blockstack-portal/releases/tag/v0.4.0
