### ISSUE TITLE
home button on hello blockstack app needs to reference proper url

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#265]
Home button on the Hello Blockstack App references `localhost:3000` in the latest blockstack portal build and needs to reference `localhost:8888`

**Comment by guylepage3** [comment]
<img width="857" alt="screen shot 2017-02-25 at 3 35 08 pm" src="https://cloud.githubusercontent.com/assets/1711854/23334618/62b1380a-fb70-11e6-9081-f37272223ddd.png">

**Comment by larrysalibra** [comment]
We should update the app to use `blockstack://` and it will automatically use the proper port depending on if you're in development mode or not.

**Comment by guylepage3** [comment]
complete. closing issue
