### ISSUE TITLE
What to call Blockstack "Portal"

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#267]
@guylepage3 @muneeb-ali @larrysalibra @shea256 @jcnelson 

From recent discussions it sounds like we are are not yet decided on what to officially call Portal. I think it is a product release that deserves its own email in 2 weeks, and we need to have a name for it before then. Let's decide here what it will be called.

I'll start with some suggestions:
- App Store
- Portal
- dApp Store

**Comment by guylepage3** [comment]
@muneeb-ali had a very good point in our one-on-one yesterday...

Portal is just simply **Blockstack**. For both internal and external communications.

So it would look something like this..

- [ ] **Blockstack** — your access to the new internet
- [ ] **Core**
- [ ] **Search**
- [ ] **Explorer**

Thoughts?

**Comment by pstan26** [comment]
+1 to Portal just being "Blockstack"

**Comment by pstan26** [comment]
Think @muneeb-ali , @guylepage3  and myself are in agreement here. Comments @shea256 @larrysalibra ?

If we are all in agreement that Portal gets called "Blockstack" _both_ internally and externally, that will help us move forward on comms stuff.

**Comment by muneeb-ali** [comment]
Let me clarify my point a little bit. I think that new users should only be exposed to the term "Blockstack". They don't have the mental bandwidth to think about any other term/product and introducing anything other than Blockstack would just confuse them. Note that we already have baggage from the Onename app and people already confuse the Onename app and Blockstack and wonder about how they're different. (This will hopefully get better with time.) 

We can keep the sub-products i.e., Portal, Core etc in our Github repos and design docs. It's OK to introduce power users and developers to new terms and sub-products. 

On the blockstack.org website, we should release macOS and Linux binaries simply saying "Download Blockstack". Right now the installer installs only Core & CLI but in the future, it can install Portal as well. But the users don't need to know that they've installed "Core" or "Portal". As far as the users are concerned they just installed Blockstack.

**Comment by pstan26** [comment]
@muneeb-ali  +100 i'm creating a Github task for this right now. 

> On the blockstack.org website, we should release macOS and Linux binaries simply saying "Download Blockstack". Right now the installer installs only Core & CLI but in the future, it can install Portal as well.

**Comment by guylepage3** [comment]
hm.. i must have misunderstood. i don't think having two names external and internal is a wise idea then.

we can easily say to the user, "install blockstack portal"

or are you thinking that this is a temporary thing? as a developer, (our only market at the moment), i would be confused as to why i am seeing "blockstack portal" in slack and then "blockstack" on the website. that becomes convoluted. imo

**Comment by vsund** [comment]
You can communicate that the download called "Blockstack" consists of different sub parts (Core, Portal, CLI) to users who want to know more. Normally you want to ship these parts together anyway.

**Comment by guylepage3** [comment]
the problem i see with the having an internal name differ from an external name is when your communications are static and there isn't a representative present. 

how do you know that the person viewing the content fits into either the external or internal segment?

**Comment by muneeb-ali** [comment]
> i would be confused as to why i am seeing "blockstack portal" in slack and then "blockstack" on the website. that becomes convoluted. imo

But our users are not in the Slack, only developers are in Slack and it's OK to tell developers about sub-products.

> how do you know that the person viewing the content fits into either the external or internal segment?

The difference is users vs. developers. 

Think about **internal workings** that developers need to know about vs. average users who just want to use Blockstack. Here is an example, most people know docker as simply docker. When a user is first exposed to docker, they just install docker. Advanced users, over time, learn about the [Docker Hub](https://hub.docker.com/) or [Docker Swarm](https://www.docker.com/cp/docker-and-kubernetes) or [Kitematic](https://github.com/docker/kitematic) or [libcontainer](https://github.com/docker/libcontainer). 

There will **always** be a need to name sub-products and libraries e.g., Core or Virtualchain. 

There will **always** be a need to introduce a simple term to new users and the **majority** of users. 

For docker that name is docker and for us that name is blockstack.

**Comment by guylepage3** [comment]
>But our users are not in the Slack, only developers are in Slack and it's OK to tell developers about sub-products.

I thought our target demographic was developers at the start? I thought we defined that a long time ago. If it has changed then a lot of our comms should be changed dramatically because they are not taking that into account.

**Comment by vsund** [comment]
@guylepage3 You have one product called Blockstack, and it has different parts. You could have a link that provides further information for users that would like to know more about details below the download (or a diagram that tells the user how the different parts acts together).

If it's less confusing you can name the download "Blockstack package" or similar.

**Comment by muneeb-ali** [comment]
Here is another example (other than docker): 

IPFS lists out their various implementations on their Github.
![image](https://cloud.githubusercontent.com/assets/669932/23435553/bec8049a-fdd5-11e6-9f87-686399f031fd.png)

But on the download page it simply says: 
![image](https://cloud.githubusercontent.com/assets/669932/23435650/fe88c182-fdd5-11e6-9fb7-834306a8364b.png)

You are installing GO IPFS but that detail is not important for someone who is installing IPFS for the first time.

At the same time, it's important to have reference implementations and default clients while leaving the door open to other implementations and other clients. 

Therefore, I propose that we do not expose new users to the sub-products like CLI, Core, and Portal and just say "Install Blockstack". The installer will give them various sub-products but the users don't need to think about that.

Similar simplification is happening with CLI and Core as well where Core now ships when you do:
> pip install blockstack

And most of the times, users will interact with Blockstack by simply using the "blockstack" command and they do not need to think about the sub-components.

**Comment by guylepage3** [comment]
@pstan26 @muneeb-ali @shea256 @larrysalibra @jcnelson,

Can I close out this issue? I believe we are all in agreement that the terms are as follows;
public —› Blockstack
internal —› Blockstack Portal

**Comment by shea256** [comment]
Yup, all set to be closed out.
