### ISSUE TITLE
blockstack-js dependency causes npm install to fail without github ssh credentials

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#274]
See https://github.com/blockstack/blockstack-js/issues/4#issuecomment-284385175

We need to update the npm `blockstack` package to one that uses `0.0.8` or newer version of `blockstack-keychains`

**Comment by shea256** [comment]
Thanks @larrysalibra added you in the other repo.

**Comment by shea256** [comment]
I think this should have been taken care of. @larrysalibra please confirm.

**Comment by shea256** [comment]
I just tested this and it has been addressed. Closing this issue.
