### ISSUE TITLE
Update portal to release version of Core 0.14.1

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#278]

**Comment by shea256** [comment]
@larrysalibra How is this different from #279?

**Comment by larrysalibra** [comment]
@shea256 #279 is updating the Core code that is distributed with the macOS app. I added [notes on that task](https://github.com/blockstack/blockstack-portal/issues/279#issuecomment-285278941).

This task is refactoring the portal api calls so that they work with 0.14.1. We'll need to change all calls to Core to send the API secret. I believe the ability to do unauthenticated calls to the Core API was removed.

**Comment by shea256** [comment]
OK great thanks for the clarification.

**Comment by larrysalibra** [comment]
Complete!
