### ISSUE TITLE
Update macOS app to include Core 0.14.1

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#279]

**Comment by larrysalibra** [comment]
As part of this task, we'll need to:

1) generate an API secret
2) store the API secret in the user's macOS Keychain
3) pass the API secret to portal 

Options for passing the API secret to Portal:
* Via the URL (and then storing it in localStorage). The downside to this is that users will not easily be able to use the Portal in their non-default browser. This would also make it challenging when developing the Portal in that we need to use multiple browsers.
* Writing it directly into the portal code that's bundled with the app. Developers working on the Portal would have to look up the API secret in their keychain and then pass it to the development instance of of the Portal (perhaps as an argument of `npm run dev`)

**Comment by shea256** [comment]
Is this process as simple as can be? Or are there things we can do to simplify the integration with Core?

**Comment by shea256** [comment]
`localStorage` would be great to avoid if possible.

Can we have the bundler generate it and store it in the proxy server, and then route API requests through that?

**Comment by larrysalibra** [comment]
Done!
