### ISSUE TITLE
Error when approving Hello Blockstack log in request

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#280]
When I try to log in to Hello Blockstack, I get an error when I click the Approve button.

I'm using the `v0.4.0` Blockstack for macOS release

<img width="1386" alt="screen shot 2017-03-07 at 10 50 37 pm" src="https://cloud.githubusercontent.com/assets/597182/23661740/8d076c76-0388-11e7-905e-3d9dc1f40206.png">

**Comment by shea256** [comment]
@larrysalibra Can you provide more details on this error? Do you think you can debug this one yourself?

**Comment by larrysalibra** [comment]
I'll try it in development mode and see if there's a more useful stack trace.

**Comment by larrysalibra** [comment]
@shea256 can you update hello blockstack to use `blockstack://`? Right now `localhost:8888` is hardcoded.

**Comment by shea256** [comment]
@larrysalibra Right now it uses the protocol handler by default and falls back to localhost:8888 if a handler wasn't set:

```js
const BLOCKSTACK_HANDLER = "web+blockstack"

export function requestSignIn(signingKey, appManifest, identityProviderURL="http://localhost:8888/auth") {
  const authRequest = makeAuthRequest(signingKey, appManifest)

  setTimeout(function() {
    window.location = identityProviderURL + "?authRequest=" + authRequest
  }, 200)

  window.location = BLOCKSTACK_HANDLER + ":" + authRequest
}```

I'm going to:

1. Update the handler from "web+blockstack" to "blockstack"
2. Have the default redirect page be something at blockstack.org, which will either let the user do a quick login or let the user download the Portal.

Question: Should it be `blockstack:<request>` or `blockstack://request`?

**Comment by shea256** [comment]
@larrysalibra Are you still seeing this error? Or is this something we can close out.

**Comment by larrysalibra** [comment]
![image uploaded from ios 4](https://cloud.githubusercontent.com/assets/597182/24199230/baebb19e-0f43-11e7-91ff-3df773e1e607.jpg)
I was still getting this problem in our mac bundled version of `v0.5.0`. Upgrading the version of Blockstack.js fixes it.

**Comment by shea256** [comment]
Closing this issue.
