### ISSUE TITLE
redesign the wallet app icon

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#282]
Redesign the Wallet App icon

**Comment by guylepage3** [comment]
<img width="1180" alt="screenshot 2017-03-08 15 32 46" src="https://cloud.githubusercontent.com/assets/1711854/23722749/8a4955da-0414-11e7-84da-819badae45c7.png">

**Comment by guylepage3** [comment]
<img width="1208" alt="screenshot 2017-03-08 15 46 51" src="https://cloud.githubusercontent.com/assets/1711854/23723257/798495be-0416-11e7-9e63-bc7cee310a77.png">

**Comment by shea256** [comment]
Nice! Although it looks very similar to Apple Wallet.

**Comment by guylepage3** [comment]
yeah..

**Comment by pstan26** [comment]
What if it had a little opening on the front where a "debit card" would live?

![screen shot 2017-03-08 at 4 33 15 pm](https://cloud.githubusercontent.com/assets/5605552/23725082/2ea42cb0-041d-11e7-9447-7b45bcc25672.png)

**Comment by guylepage3** [comment]
<img width="1298" alt="screenshot 2017-03-08 17 35 35" src="https://cloud.githubusercontent.com/assets/1711854/23727344/a82f88ba-0425-11e7-96d9-fe6f1345d92f.png">

**Comment by guylepage3** [comment]
<img width="1010" alt="screenshot 2017-03-08 17 42 27" src="https://cloud.githubusercontent.com/assets/1711854/23727580/9e6f485a-0426-11e7-8587-f9f9755a1bb1.png">

**Comment by shea256** [comment]
Nice! These are looking really good.

**Comment by guylepage3** [comment]
<img width="1008" alt="screenshot 2017-03-08 17 54 14" src="https://cloud.githubusercontent.com/assets/1711854/23727965/4344adba-0428-11e7-9c71-35baae774e40.png">

**Comment by guylepage3** [comment]
<img width="1001" alt="screenshot 2017-03-08 17 59 31" src="https://cloud.githubusercontent.com/assets/1711854/23728093/ff4e5eb6-0428-11e7-8d43-aeb945bc89b2.png">

**Comment by guylepage3** [comment]
<img width="989" alt="screenshot 2017-03-08 18 37 30" src="https://cloud.githubusercontent.com/assets/1711854/23729161/5093f5d8-042e-11e7-87f8-88295efcdb3a.png">

**Comment by guylepage3** [comment]
going with the last one above. flat design.

**Comment by larrysalibra** [comment]
FWIW, I like the purple one. The last one looks like a file manager icon instead of a wallet icon to me.

<img width="307" alt="screen shot 2017-03-09 at 3 57 43 pm" src="https://cloud.githubusercontent.com/assets/597182/23741001/2f430c80-04e1-11e7-9069-a8b20f114298.png">

**Comment by guylepage3** [comment]
<img width="1089" alt="screenshot 2017-03-09 15 22 10" src="https://cloud.githubusercontent.com/assets/1711854/23769103/3ca5559a-04dc-11e7-9259-cfca8b6208d0.png">

**Comment by guylepage3** [comment]
<img width="967" alt="screenshot 2017-03-09 15 35 43" src="https://cloud.githubusercontent.com/assets/1711854/23769640/12bb615a-04de-11e7-9d04-fa38baab6e54.png">

**Comment by guylepage3** [comment]
Thought about this a bit more and feel that our icon set needs to be more consistent with one another. Reopening this issue

**Comment by pstan26** [comment]
[image: Inline image 1]
What do you think about conveying a better sense of security on the wallet
with something like a simple bank vault image. (unless we are planning on
creating the "vault" app)

**Comment by guylepage3** [comment]
New wallet icon.

<img width="1022" alt="screenshot 2017-03-16 12 16 06" src="https://cloud.githubusercontent.com/assets/1711854/24006496/5e7b7a30-0a42-11e7-8bb4-d8df297e90c7.png">

**Comment by shea256** [comment]
Nice @guylepage3!

**Comment by guylepage3** [comment]
adjusted the size slightly..

<img width="970" alt="screenshot 2017-03-16 12 18 06" src="https://cloud.githubusercontent.com/assets/1711854/24006593/a5e783b4-0a42-11e7-8df7-4ad31c7c3025.png">

**Comment by guylepage3** [comment]
Final. Final

<img width="983" alt="screenshot 2017-03-16 12 24 00" src="https://cloud.githubusercontent.com/assets/1711854/24006920/744d63cc-0a43-11e7-8f33-fc47c9361690.png">

**Comment by guylepage3** [comment]
<img width="1023" alt="screenshot 2017-03-16 15 21 48" src="https://cloud.githubusercontent.com/assets/1711854/24014712/5a964412-0a5c-11e7-883f-bc53fcc041bd.png">

**Comment by pstan26** [comment]
Looks terrific
