### ISSUE TITLE
Create a Discourse plugin packaging OmniAuth Blockstack strategy

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#283]

**Comment by shea256** [comment]
It looks like we can get away with signing the requests in the frontend and verifying the responses in the backend.

Here's the auth library we have in JS:

https://github.com/blockstack/blockstack-js/tree/master/src/auth

**Comment by larrysalibra** [comment]
Great

**Comment by larrysalibra** [comment]
Done and installed on our forum: https://github.com/larrysalibra/discourse-blockstack
