### ISSUE TITLE
Create an OmniAuth Blockstack authentication strategy

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#285]

**Comment by larrysalibra** [comment]
This is almost complete:

As of now we can:

* Generate a Blockstack Auth request
* Redirect the user to Blockstack Portal
* Verify the Blockstack Auth response & signature
* Receive claimed username

We still have to:

Verify the claimed username is owned by the address

**Comment by larrysalibra** [comment]
Can now verify claimed username is owned by address: https://github.com/blockstack/omniauth-blockstack/commit/db62d368c3681c938898a1da9f2373c68a74ccfe

**Comment by shea256** [comment]
Hell yeah!

**Comment by larrysalibra** [comment]
We now verify the claimed username is owned by the address: https://github.com/blockstack/omniauth-blockstack/commit/db62d368c3681c938898a1da9f2373c68a74ccfe
