### ISSUE TITLE
Update the forum usernames so that usernames created outside of Blockstack Auth have a different suffix (like .id)

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#286]

**Comment by shea256** [comment]
@larrysalibra What do you think we should do for this one?

Do you like the idea of having all Blockstack users sign in as "USERNAME.id" and all existing forum users sign in as "USERNAME.local"?

The second TLD can be something other than "local". Just an example to ensure that we have the ability to merge two username "namespaces".

**Comment by larrysalibra** [comment]
https://github.com/larrysalibra/discourse-blockstack/commit/f4e9af076d29bf882da0548be8855b120d2d0bf5
