### ISSUE TITLE
Chore: update the portal codebase to trim out unnecessary utils replace them with the functions in Blockstack Auth

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#288]

**Comment by shea256** [comment]
Writing some notes on this task...

In `profile-utils.js` we should be able to get rid of the following functions and replace them with their equivalents in `blockstack.js`:

- `verifyToken` with `verifyProfileToken`
- `getProfileFromTokens` with `extractProfile`

We can also get rid of `verifyTokenRecord` and just unpack the token records into tokens (`verifyProfileToken(tokenRecords[0].token)`).

We should also update `signProfileForUpload` so it uses the `signProfileToken` function in `blockstack.js`.

In `profile-utils.js` we should be able to get rid of the following functions and replace them with their equivalents in `blockstack.js`:

- `makeZoneFileForHostedProfile` with `makeProfileZoneFile`
- `getTokenFileUrlFromZoneFile` with `getTokenFileUrl`

**Comment by larrysalibra** [comment]
Done.
