### ISSUE TITLE
second home button appearing on edit profile view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#292]
Remove second home button that appears on the edit profile view

<img width="229" alt="screenshot 2017-03-07 14 51 27" src="https://cloud.githubusercontent.com/assets/1711854/23674965/bdb6e4ca-0345-11e7-9776-1b293b26c447.png">

**Comment by guylepage3** [comment]
best way to resolve this issue is to make the **home button** it's own component

**Comment by guylepage3** [comment]
compete

**Comment by shea256** [comment]
@guylepage3 Nice!

Only thing is now the home button now has disappeared from the Account and Wallet apps.

Reopening this issue so we can address this here. Alternatively we can create a separate issue for this.

**Comment by guylepage3** [comment]
Oh. 😖 Let me add that back in..

**Comment by guylepage3** [comment]
added new home button structure to Profiles, Wallet and Account apps.
