### ISSUE TITLE
Add menu options to macOS app to go directly to Profiles, Wallet & Account.

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#295]

**Comment by larrysalibra** [comment]
<img width="177" alt="screen shot 2017-03-08 at 9 30 43 pm" src="https://cloud.githubusercontent.com/assets/597182/23705933/fcec40f2-0446-11e7-9cf6-034cbb22d1d1.png">
<img width="285" alt="screen shot 2017-03-08 at 9 30 55 pm" src="https://cloud.githubusercontent.com/assets/597182/23705935/fe69c09e-0446-11e7-9e68-7c5b5dcf5272.png">

Let me know what you think of the naming in these menus ^^ @shea256 @jcnelson @muneeb-ali @guylepage3 @pstan26

**Comment by guylepage3** [comment]
@larrysalibra what's the difference between the two menus?

**Comment by shea256** [comment]
@guylepage3 The second one is shown when you hold down the option key and then click on the menu tray item.

**Comment by shea256** [comment]
And @larrysalibra nice work! Really liking these quick links.

**Comment by guylepage3** [comment]
>@guylepage3 The second one is shown when you hold down the option key and then click on the menu tray item.

How does the user know to do that?

**Comment by larrysalibra** [comment]
> How does the user know to do that?

@guylepage3 That's how menu bar icons on macOS typically work: Try option-clicking the wifi, bluetooth, volume, battery or time machine icons. In each, you'll get advanced options. If you option-click the notification panel menu bar icon you'll toggle macOS's "Do not disturb" setting.

We could add an explanation note to the README in the repository. It's only important for those of us working on the portal.

**Comment by guylepage3** [comment]
>That's how menu bar icons on macOS typically work
Ha! I had no idea about that trick
