### ISSUE TITLE
add a storage app to the dashboard

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#297]
@guylepage3 @larrysalibra We discussed pulling out the storage management operations into a separate storage app.

Think we should go forward on this?

**Comment by guylepage3** [comment]
I definitely feel that in pulling storage out we will better communicate to users that storage is something that we have solved and therefore feel it's quite important.

**Comment by shea256** [comment]
Awesome, let's add it to v0.5 then.

**Comment by larrysalibra** [comment]
Yes. Good idea. I'd eventually like to know what's in my storage as well.

**Comment by shea256** [comment]
@larrysalibra I'm assigning this one to you. We can make an enclosing app object just like the ones for the Profiles app and the Wallet app.

**Comment by guylepage3** [comment]
@larrysalibra can you work on this today and I will follow up with a quick and dirty live design on this at the end of the day? I am currently working on the new icon for this app.

**Comment by larrysalibra** [comment]
Sure. @guylepage3 I'll work on it in a few minutes.

**Comment by larrysalibra** [comment]
@shea256 @guylepage3 besides connect to dropbox & coming soon buttons for other storage providers, what else should be in the storage app in this sprint?

**Comment by shea256** [comment]
That's all I can think of for now. Let's make it really simple.

**Comment by larrysalibra** [comment]
<img width="1123" alt="screen shot 2017-03-10 at 4 05 46 am" src="https://cloud.githubusercontent.com/assets/597182/23768422/e0ef2170-0546-11e7-9f69-47f6e24ed363.png">
<img width="532" alt="screen shot 2017-03-10 at 4 12 34 am" src="https://cloud.githubusercontent.com/assets/597182/23768703/d5600d0a-0547-11e7-9c6d-2b2f543c39bb.png">

Complete ^^

**Comment by larrysalibra** [comment]
@guylepage3 you should be good to go. let me know if you find any problems.

I put a temporary icon in pending completion of #300. 

Now that most users won't need to touch the API settings page (since it used to have connect to dropbox), I demoted it in the Account app:

<img width="604" alt="screen shot 2017-03-10 at 4 18 02 am" src="https://cloud.githubusercontent.com/assets/597182/23768978/c0af3f1a-0548-11e7-9767-48dcf983b283.png">

**Comment by larrysalibra** [comment]
I was thinking we should add a 1-2 sentence description to the Storage app page explaining to users why they would want to connect/disconnect their cloud storage provider and what it will be used for. Thoughts? @shea256 @guylepage3

**Comment by larrysalibra** [comment]
I'm going with "Your profile and app data will be securely stored in the storage providers you connect." for now. We can improve on this.
