### ISSUE TITLE
add an indicator that alternative storage options are coming soon

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#298]
@guylepage3 @larrysalibra 

I was thinking during the demo of the portal yesterday that it was a bit problematic that we only have Dropbox as a storage option. It does not convey that Blockstack is "storage agnostic."

That said, I don't feel it's the best use of our time right now to add Google Drive, Amazon Cloud Drive, or Microsoft One Drive. We should save this for a future sprint.

However, we can probably get most of the benefit of demonstrating that Blockstack works with multiple storage options by adding grayed out buttons like "Connect Google Drive".

What do you think of this route?

**Comment by guylepage3** [comment]
I like it. we should also say "coming soon..." though so that users are aware this is just a tease.

**Comment by shea256** [comment]
Coming soon over the top of the button? Or to the side?

These buttons would need to go in the second page of the welcome modal and in the storage settings section.

This directly relates to #297.

**Comment by guylepage3** [comment]
directly above the button separating the greyed out buttons from the dropbox button
