### ISSUE TITLE
design storage app icon

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#300]
Design a new storage app icon for the home screen

**Comment by guylepage3** [comment]
@shea256 @larrysalibra thoughts on direction for the app icon. Here are the directions that i was thinking we could go;
1. Hard drive
1. Server
1. Device
1. Vault
1. Safe
1. Lock

Please let me know which you guys are thinking is more representational of the app. :D

**Comment by larrysalibra** [comment]
Vault or safe conveys more the benefits of Blockstack storage compared to centralized solutions. Both of those are containers that can store information securely.

**Comment by shea256** [comment]
I like vault and safe, as long as there's a little spin that indicates it's for data.

**Comment by guylepage3** [comment]
>as there's a little spin that indicates it's for data

There probably won't be for a quick and dirty icon that first and foremost has to look good.

**Comment by shea256** [comment]
OK that's fine then for now.

**Comment by guylepage3** [comment]
<img width="1023" alt="screenshot 2017-03-16 15 21 48" src="https://cloud.githubusercontent.com/assets/1711854/24014697/4cfb3380-0a5c-11e7-9455-73b9cc8b8161.png">
