### ISSUE TITLE
authResponse redirect url improperly generated 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#323]
If the callback url for an authentication request includes existing query parameters, the `authResponse` field isn't properly appended to the callback URL. Our current login simply appends "?authResponse=<token>" resulting in urls like this:

`http://localhost:4000/auth/blockstack/callback?sso=bm9uY2U9OGM4NDcyZDY3OTU2OTczM2FkOTU2MTExZjRlMjFhYWMmcmV0dXJu%0AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmxvY2FsaG9zdCUzQTMwMDAlMkZzZXNz%0AaW9uJTJGc3NvX2xvZ2lu%0A&sig=c9671abce0d2844d4f1b3db18f49be514b7e5f69e69ddbfa30c867b32814ac13?authResponse=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJqdGkiOiIyZDdhOGY4Yy0yOWZkLTQ3OWQtYjhmNC0xZGJlYWEwMmE0NGYiLCJpYXQiOjE0ODk5MzQxNDAsImV4cCI6MTQ5MjYxMjU0MCwiaXNzIjoiZGlkOmJ0Yy1hZGRyOjFFWHdyejJFM1d2eGhkZVJCMUFyS3RkRTVOS3RLQzdFZHgiLCJwdWJsaWNLZXlzIjpbIjAzMTY1NTliZDBlNDk4ZGEzZjQyZjZiZjAzNGNiNWNjY2NlOTUzMmY2ZWIyNzYxMGE2OWIxNmExNTBmMjY4OTZlZiJdLCJwcm9maWxlIjp7IkB0eXBlIjoiUGVyc29uIiwiQGNvbnRleHQiOiJodHRwOi8vc2NoZW1hLm9yZyIsImdpdmVuTmFtZSI6ImhpIiwiZmFtaWx5TmFtZSI6Im9rIiwiaW1hZ2UiOlt7IkB0eXBlIjoiSW1hZ2VPYmplY3QiLCJuYW1lIjoiYXZhdGFyIiwiY29udGVudFVybCI6IiJ9LHsiQHR5cGUiOiJJbWFnZU9iamVjdCIsIm5hbWUiOiJhdmF0YXIiLCJjb250ZW50VXJsIjoiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy9jMGcyd2d5dWdkd3AydHovYXZhdGFyLTE_ZGw9MSJ9XX0sInVzZXJuYW1lIjoiZGV2bmFtZTIuaWQifQ.HKdPBIAh2FOZ8DxZNxN1nnW1vj3ezQTtFgJ7dc4s9DbJGS8uoD3rU0nCcuaJZwbNz5Oq9OQYBy_UlVdB2j1JmA`

**Comment by larrysalibra** [comment]
@shea256 modified `blockstack.js` so that the redirect is handled properly. closing

**Comment by shea256** [comment]
@larrysalibra I also addressed this issue here: https://github.com/blockstack/blockstack-portal/commit/c8212b65da635dfee8ba8f43a7741a9f2a530f68#diff-c7542e5ed21d2c42c51d984d4f4dbf5cR60
