### ISSUE TITLE
macOS: Research different auto update frameworks

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#329]
Sparkle: https://sparkle-project.org

**Comment by vsund** [comment]
I don't know how this matches your needs, but might be a look worth while researching:
https://theupdateframework.github.io

**Comment by larrysalibra** [comment]
@vsund thanks. This looks interesting. We should definitely look at this in future when we have decentralized updates signed by Blockstack names.

In the meantime, using something off-the-shelf like Sparkle seems like the way to go. It's open source and won't install updates unless they come signed with Apple's Developer ID and the author is the same.

**Comment by larrysalibra** [comment]
Decided to go with Sparkle. See #355 for integration progress. Closing.
