### ISSUE TITLE
npm run dev doesn't parse api password properly

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#333]
`npm run dev -- --api_password <secret>` doesn't work (i've temporarily updated our readme to instruct users to run the two processes separately.)

**Comment by larrysalibra** [comment]
The`npm run dev` that executed `concurrently` didn't pass arguments on to the gulp tasks, so I removed it and replaced it with the old `dev-ui` task.

I've updated instructions to direct those developing on macOS to use our mac app which provides CORS proxy and a Core node. Those developers don't need to run a separate CORS proxy. 

Linux users can run each task separately.

**Comment by petepacific** [comment]
@larrysalibra I am on Debian Jessie and get the following error when I run 'npm run dev-proxy':

npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development ./node_modules/.bin/gulp proxy

Is there anything I need to update?
Thank you
