### ISSUE TITLE
5 second lag upon launching Blockstack

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#338]
There seems to be a 5 second lag upon launching Blockstack to the opening of the portal home screen in my default web browser. There is nothing to indicate that the action of Blockstack is opening.

**Comment by larrysalibra** [comment]
The easiest short term solution to this is to open the portal home screen immediately after the portal web proxy starts. By the time the user starts using the portal and making core api requests, the api should have started. I just implemented this.

In the long term we can either try to speed up Core start up and/or add a loading screen.

**Comment by larrysalibra** [comment]
My portal was opening before the portal proxy was ready to handle requests. I added a 1/2 second delay.
