### ISSUE TITLE
Cannot back out of sign in to create profile

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#339]
![screen shot 2017-03-22 at 3 42 52 pm](https://cloud.githubusercontent.com/assets/5605552/24217604/cf272e72-0f16-11e7-8a81-26b36b0bd545.png)

I cannot back out of this modal to create a profile (what the modal is telling me to do in order to proceed).

Also copyedit recommendation: instead of "you must have created a profile to login" ∆ it to "Complete your Blockstack profile to login"

@larrysalibra

**Comment by pstan26** [comment]
ps: I can't assign it to anyone since I don't have admin rights over this repo

**Comment by pstan26** [comment]
Can someone claim this? Can't assign.  @shea256 @larrysalibra

**Comment by shea256** [comment]
Fixed here: https://github.com/blockstack/blockstack-portal/commit/f7a7d948752e9f235b22961ac9ba977cd6f46c82

Closing.
