### ISSUE TITLE
Wallet bitcoin address takes a long time to appear

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#341]
![screen shot 2017-03-23 at 12 06 52 pm](https://cloud.githubusercontent.com/assets/5605552/24257445/4c2a86b2-0fc1-11e7-8415-701ff017fb93.png)

cc @larrysalibra @shea256

**Comment by larrysalibra** [comment]
Can you take a look at your browser's error console and share a screenshot?

Is Core running? (try visiting http://localhost:6270/v1/names/muneeb.id and see if anything loads)

**Comment by pstan26** [comment]
![screen shot 2017-03-23 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/5605552/24257950/aada7626-0fc2-11e7-8f47-ec7082199116.png)

**Comment by pstan26** [comment]
![screen shot 2017-03-23 at 12 17 32 pm](https://cloud.githubusercontent.com/assets/5605552/24257963/b843850a-0fc2-11e7-8a3e-d0b1f292d26c.png)

**Comment by larrysalibra** [comment]
Are you using the Mac app? Which version?

**Comment by pstan26** [comment]
Yea mac app. v0.5.1 --> will upgrade to v0.5.2 and see if that helps

**Comment by pstan26** [comment]
Upgraded and it didn't change anything.

**Comment by larrysalibra** [comment]
Can you quit the app, and run it from the Terminal? It will print out a bunch of logging information. The log information might have some sensitive info..copy it and PM it to me on Slack.

To run it from Terminal (assuming you dragged Blockstack to the Applications folder), run the following:
 `/Applications/Blockstack.app/Contents/MacOS/Blockstack`

**Comment by pstan26** [comment]
send you a DM with the file. Wallet works in the terminal only for now.

**Comment by pstan26** [comment]
the wallet address opens 10 seconds after i open the page in chrome (too long for me to think it will work before exiting)

**Comment by larrysalibra** [comment]
@pstan26 Can you load the wallet with the network section of the developer tools open and see how long it takes for the payment address to load? You'll have to hold your mouse pointer over the colored bar that corresponds with payment address request. See my screenshot below for an example:

<img width="1408" alt="screen shot 2017-03-24 at 1 26 14 am" src="https://cloud.githubusercontent.com/assets/597182/24261162/0d74f46e-1031-11e7-96ec-ce9b336767be.png">

**Comment by pstan26** [comment]
![screen shot 2017-03-23 at 1 42 23 pm](https://cloud.githubusercontent.com/assets/5605552/24261869/c83ab94a-0fce-11e7-8631-90556483a6be.png)
![screen shot 2017-03-23 at 1 42 46 pm](https://cloud.githubusercontent.com/assets/5605552/24261870/c83abe90-0fce-11e7-8067-e044f0c74cfb.png)

**Comment by shea256** [comment]
Looks like 20 seconds on "Waiting (TTFB)".

**Comment by larrysalibra** [comment]
@pstan26 What's the "VM270" script that's initiating the request? On mine it is `fetch` handling the request. Can you try disabling your Chrome extensions?

**Comment by shea256** [comment]
I get:

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
```

**Comment by larrysalibra** [comment]
@shea256 is your Core running?

**Comment by pstan26** [comment]
turned off all extensions and it is still taking forever

![screen shot 2017-03-23 at 1 53 32 pm](https://cloud.githubusercontent.com/assets/5605552/24262368/2d028c12-0fd0-11e7-98bb-c3259887dfdf.png)

**Comment by shea256** [comment]
I just downloaded 0.5.2 and started that app. Looks like Core wasn't running before.

Here are my stats:

![screen shot 2017-03-23 at 1 57 19 pm](https://cloud.githubusercontent.com/assets/994646/24262535/b48a25a0-0fd0-11e7-90bc-7453dd91c67c.png)

As you can see, it takes 20 seconds, just like it does with Patrick.

**Comment by larrysalibra** [comment]
@shea256 @pstan26 Below are instructions to test the speed of payment address look up directly from Core bypassing the Portal. The idea is to see if it's only slow loading the address from the Portal or if it's also slow loading the address outside of Core. The objective of this exercise is to determine if our issue is in the Portal or in Core.

1. Open Terminal
1. Create a new file, `curl-format.txt`, and paste in:
```
    time_namelookup:  %{time_namelookup}\n
       time_connect:  %{time_connect}\n
    time_appconnect:  %{time_appconnect}\n
   time_pretransfer:  %{time_pretransfer}\n
      time_redirect:  %{time_redirect}\n
 time_starttransfer:  %{time_starttransfer}\n
                    ----------\n
         time_total:  %{time_total}\n
```
3. In Chrome, click on the `payment_address` request followed by the "Headers" tab. Expand the "Request Headers" section, select the entire line that starts with `authorization` and copy it. (See screenshot below)

<img width="832" alt="screen shot 2017-03-24 at 2 11 14 am" src="https://cloud.githubusercontent.com/assets/597182/24263127/2f0a9e16-1037-11e7-99ee-8887f93d604b.png">


4. Back in Terminal, paste in the following command replacing the text `PASTE_AUTH_HEADER_HERE` with the line you copied in the previous step:

```
curl -w "@curl-format.txt" --header "PASTE_AUTH_HEADER_HERE" http://localhost:6270/v1/wallet/payment_address
```

5. Press enter to run the command.

Please reply with your results.

Mine are here:

```
{"address": "3Ht2PzmsT4gy4EpBTp7FKco239ZiHvXdUP"}  time_namelookup:  0.014
       time_connect:  0.015
    time_appconnect:  0.000
   time_pretransfer:  0.015
      time_redirect:  0.000
 time_starttransfer:  0.056
                    ----------
         time_total:  0.056
```

**Comment by shea256** [comment]
Never mind, there is an authorization header shown in the first case.

**Comment by shea256** [comment]
Here are the headers...

### Request 1:

![screen shot 2017-03-23 at 2 22 18 pm](https://cloud.githubusercontent.com/assets/994646/24263781/997b1cac-0fd4-11e7-88e7-5c223a94c169.png)

### Request 2:

![screen shot 2017-03-23 at 2 23 48 pm](https://cloud.githubusercontent.com/assets/994646/24263727/66c086b2-0fd4-11e7-986f-aa03ff1a8a79.png)

**Comment by larrysalibra** [comment]
Thanks guys. This might be related to still having fetches in the React components. They're scheduled to be moved out in this sprint (https://github.com/blockstack/blockstack-portal/issues/249). Let's see if this issue still exists after that.

**Comment by pstan26** [comment]
Ok @larrysalibra , do you have a rough ETA on when that would be? (by end of next week?) Would be good to resolve by the time we would publish a blogpost on signing into the forum.

**Comment by larrysalibra** [comment]
@pstan26 I can work on it first thing tomorrow. It won't take long to make the changes. I'll have a new build for you tomorrow morning NYC time to try. I can't replicate the problem on my side, so I'll need you and @shea256 to see if the changes resolve the issue.

**Comment by pstan26** [comment]
Happy to! thank you for the sense of urgency re: this -- our readers will be delighted

**Comment by shea256** [comment]
@larrysalibra @pstan26 This should fix the problem:

https://github.com/blockstack/blockstack-portal/commit/8b601acb039b8a325d4e21babff94c9c27ae3238

**Comment by shea256** [comment]
Closing this issue. Please reopen if the problem persists.

**Comment by pstan26** [comment]
it fixes the problem when navigating within the portal itself, but if you put the wallet URL in the browser manually or navigate to the wallet from the little blockstack icon at the top bar of the mac screen, it has the same problem.
![screen shot 2017-03-23 at 4 59 27 pm](https://cloud.githubusercontent.com/assets/5605552/24270078/1a04f13a-0fea-11e7-8a25-9a2cbc963874.png)


![screen shot 2017-03-23 at 4 55 23 pm](https://cloud.githubusercontent.com/assets/5605552/24270064/0c5a118c-0fea-11e7-9624-8ae5cbab9650.png)

**Comment by shea256** [comment]
@pstan26 I mean on the developer build. You'll have to try that to see if it works for you.

You must run `npm run dev-ui` and then go to `localhost:3000`. No need to worry about this right now. I can help you get set up with it later.

Or you can wait until we push a new build.

**Comment by pstan26** [comment]
Sounds good, assuming this is the same build we will offer in the blogpost. Moving on now. Thank you!

**Comment by larrysalibra** [comment]
Latest `v0.6` build freezes at "Loading address...` for me on first load in both Safari and Chrome. On subsequent loads it works.

Suspect this is related to #249 (there's still a balance call happening in a reach component in that view).


<img width="1041" alt="screen shot 2017-03-24 at 7 35 33 pm" src="https://cloud.githubusercontent.com/assets/597182/24292652/366d0f80-10c9-11e7-80a0-413833c1b8b0.png">

**Comment by larrysalibra** [comment]
Moving the fetches in Balance solved the stuck at "Loading address..." problem for me.

**Comment by larrysalibra** [comment]
@pstan26 @shea256 I've made a new build. Can you give it a try and verify that this problem no longer occurs? https://github.com/blockstack/blockstack-portal/releases/tag/v0.5.3

**Comment by larrysalibra** [comment]
Closing this. Please open a new issue if it re-appears.
