### ISSUE TITLE
Redirect new users to the wallet to add funds prior to registering

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#343]
Right now it is unclear that I can't just register a Blockstack ID for free. We need to:

- [ ] display the needed balance to register a name 
- [ ] direct people to their wallet through text or a button
- [ ] change the word "username" to Blockstack ID

![screen shot 2017-03-23 at 3 01 59 pm](https://cloud.githubusercontent.com/assets/5605552/24265400/cfce41e4-0fd9-11e7-8d19-e3528811e840.png)

**Comment by pstan26** [comment]
need access to this repo, otherwise @shea256 or @larrysalibra must assigne themselves. We need this fixed before the blogpost goes out.

**Comment by larrysalibra** [comment]
We have an outstanding issue for this: https://github.com/blockstack/blockstack-portal/issues/232

It isn't trivial. @shea256 @guylepage3 and I discussed it and decided it wasn't worth the engineering effort in this sprint. 

Something faster we could do is check the user's balance and, if it's zero, display an alert with a link to the wallet saying they'll need to add bitcoin to register a name. Thoughts?

**Comment by pstan26** [comment]
That sounds **much** better than what we have. May I ask, what part of what I mentioned is non-trivial? 

Perhaps we could add some static text like "Add $2 of Bitcoin in order to register and once you've submitted your name request do not turn your computer off for 4 hrs (!!!)"

**Comment by larrysalibra** [comment]
> what part of what I mentioned is non-trivial

see this comment -> https://github.com/blockstack/blockstack-portal/issues/232#issuecomment-279868155

**Comment by larrysalibra** [comment]
@guylepage3 are you working on this? (it's in doing)

**Comment by guylepage3** [comment]
@larrysalibra no. I am not working on this. I'll move it out of doing.

**Comment by pstan26** [comment]
I see, then I think static text stating "be sure your wallet has $2 worth of bitcoin prior to registering" may be the very best solution at the moment, especially if people are reading our upcoming blog post on Monday about signing in to the forum and want to create their own Blockstack ID in the portal for the first time. If we manage their experience and expectations they might come back.

**Comment by shea256** [comment]
Sounds good @pstan26. Thanks for this.

**Comment by larrysalibra** [comment]
If the user's wallet balance is 0, they'll see the following clickable alert:
<img width="733" alt="screen shot 2017-03-30 at 7 02 26 pm" src="https://cloud.githubusercontent.com/assets/597182/24501299/7ee9e380-157b-11e7-9dff-c8fc7b3dcf25.png">

I hardcoded this message which suggests that users send 0.01 btc, which should be enough for most
<img width="949" alt="screen shot 2017-03-30 at 6 58 31 pm" src="https://cloud.githubusercontent.com/assets/597182/24501149/e6982682-157a-11e7-8bd1-07ed0d0bac3d.png">

If users have bitcoin in their wallet and try to buy a name that costs more than the amount they have, they'll be warned and told how much more bitcoin they should deposit with a click-to-go-to-wallet alert.

We can further improve the process as part of #232.

@pstan26 thoughts?

**Comment by pstan26** [comment]
@larrysalibra Looks like the screenshot is showing the wallet (pardon my confusion)-- is this supposed to be an example of a popup alert on the name registry itself? Where I think people risk being most confused is at the name registry itself -- a static prompt there seems a higher priority than the wallet. Just want to make sure I clearly understand the direction here. :-)

**Comment by larrysalibra** [comment]
@pstan26 sorry about that! I meant to delete the screenshot where I wrote `0.1 bitcoin` and ended up deleting the other. Let's try this again:

If the user's wallet balance is 0, they'll see the following clickable alert:
<img width="611" alt="screen shot 2017-03-30 at 6 47 46 pm" src="https://cloud.githubusercontent.com/assets/597182/24513188/29c91ee8-15a3-11e7-8b19-19f620603832.png">

I hardcoded this message which suggests that users send 0.01 btc, which should be enough for most names:
<img width="733" alt="screen shot 2017-03-30 at 7 02 26 pm" src="https://cloud.githubusercontent.com/assets/597182/24513223/3feff886-15a3-11e7-8fa8-1c34390c8758.png">

**Comment by pstan26** [comment]
Thanks @larrysalibra why don't we set expectations right up front and include "at least 0.01 bitcoins" in the alert message?

Definitely don't want to increase scope, but if it were possible to display the bitcoin wallet address in the alert it means less clicking and less dropoff. People only have so much cognitive overhead and this part scares me most from an adoption standpoint.

**Comment by larrysalibra** [comment]
@pstan26 both suggestions are great. Thanks for the feed back!

**Comment by larrysalibra** [comment]
@pstan26 change it to this:
<img width="575" alt="screen shot 2017-04-02 at 5 19 23 pm" src="https://cloud.githubusercontent.com/assets/597182/24585926/8e0fad82-17c8-11e7-9f97-bb602388a8c0.png">

**Comment by larrysalibra** [comment]
@pstan26 i'm going to close this.
