### ISSUE TITLE
split up components by adding app directories

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#345]
The `components` directory is beginning to get a bit confusing in regards to which components belong to what application. Let's split the components up by adding app specific directories.

**Comment by shea256** [comment]
This has been largely taken care of with this commit: https://github.com/blockstack/blockstack-portal/commit/eb5fa5d57821b1477d48bb67aba855f187e9482b. I'd say I'm 80% of the way there. I still need to work on a few more components. For this reason, i'm temporarily keeping it in branch `v0.6-restructured`.

**Comment by larrysalibra** [comment]
I've merged progress up to this point. https://github.com/blockstack/blockstack-portal/commit/2bac448ec0fb845eb269c769ae010d379f1f3572

@shea256 if there's more to come, let me know. otherwise, you can close out this issue.

**Comment by shea256** [comment]
Closing.
