### ISSUE TITLE
design placeholder app icon

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#346]
Our avatar placeholder:

https://github.com/blockstack/blockstack-portal/blob/master/app/images/avatar.png

We need something for when the developer hasn't set an icon. We can look to other app platforms like Facebook and see what they do.

**Comment by guylepage3** [comment]
![app-icon-generic 2x](https://cloud.githubusercontent.com/assets/1711854/24665718/43b56960-192c-11e7-9bd5-2bc44ef3c032.png)
