### ISSUE TITLE
Funds sent to wallet in portal don't display

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#347]
I sent $15 worth of BTC to my wallet in my portal so I could register a name and complete another [task](https://github.com/blockstack/blockstack/issues/246) but the funds are not showing up in the portal. Core sees the funds, but Portal does not.

Wallet address: 3EZGez2HAFnEEJgiUC1GDd8rNUChg954ad

![screen shot 2017-03-23 at 6 40 12 pm](https://cloud.githubusercontent.com/assets/5605552/24273590/7f14d392-0ff9-11e7-9d5e-dc0a7e82c7a7.png)
![screen shot 2017-03-23 at 6 40 28 pm](https://cloud.githubusercontent.com/assets/5605552/24273591/7f170cb6-0ff9-11e7-81cd-171c4069616c.png)

**Comment by pstan26** [comment]
cc @larrysalibra @shea256  (I can't assign tasks in /blockstack-portal yet) :-P

**Comment by shea256** [comment]
Thanks @pstan26 you should be able to assign tasks now. I just assigned this task to @larrysalibra to take a look at.

**Comment by larrysalibra** [comment]
Thanks for reporting this. Taking a look at it now. 

@pstan26 there's a bug label that you can use instead of adding "[bug]:" to the title.

**Comment by larrysalibra** [comment]
I believe this was related to the fetches in the balance component which I've now moved out.

I tested this with @pstan26 's address and the balance shows up for me:

<img width="622" alt="screen shot 2017-03-24 at 8 33 47 pm" src="https://cloud.githubusercontent.com/assets/597182/24295991/31a46b56-10d8-11e7-84dc-e778b8d2bd88.png">

@pstan26 I've made a new build. Can you give it a try and see if this bug still happens for you? https://github.com/blockstack/blockstack-portal/releases/tag/v0.5.3

**Comment by pstan26** [comment]
@larrysalibra 

network requests:
![screen shot 2017-03-24 at 12 07 26 pm](https://cloud.githubusercontent.com/assets/5605552/24302870/8078e3a4-108a-11e7-8048-9fc4123e93c6.png)

errors in console
![screen shot 2017-03-24 at 12 07 06 pm](https://cloud.githubusercontent.com/assets/5605552/24302896/94367898-108a-11e7-8bab-8bca38319568.png)

**Comment by larrysalibra** [comment]
Can you try to go to the account app, click API settings and then the reset API button? 

Each time we make changes to the API, users need to reset it.

We plan to fix that in this task:
https://github.com/blockstack/blockstack-portal/issues/229

**Comment by larrysalibra** [comment]
You'll need to reconnect your Dropbox (sorry I know it's annoying. We'll fix that in #245)

**Comment by pstan26** [comment]
Yaaaay! works :-)
