### ISSUE TITLE
ui build of the wallet app design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#351]
UI build of the new wallet app design seen here: [#242: design the wallet app](https://github.com/blockstack/blockstack-portal/issues/242)

**Comment by guylepage3** [comment]
Pulling in @shea256's set of requirements for the design of the wallet... 
- https://github.com/blockstack/blockstack-portal/issues/242#issuecomment-289144393

## Requirements

1. A large balance display that appears on all tabs.
1. Three tabs:
    1. `Activity`: list of historical transactions (this will be blank at first)
    1. `Receive`: displays (a) a bitcoin address (b) a QR code.
    1. `Send`: displays (a) a "To" field (b) an "Amount" field (c) a "Password" field

**Comment by guylepage3** [comment]
We currently have `deposit` & `withdraw`.

@shea256, @larrysalibra, @pstan26 I wanted to get your opinion on what we should include for this sprint's build for requirements?

**Priority**
- [ ] Balance (prominent)
- [ ] `Receive`: displays (a) a bitcoin address (b) a QR code.
- [ ] `Send`: displays (a) a "To" field (b) an "Amount" field (c) a "Password" field

**Secondary**
- [ ] `Activity`: list of historical transactions (this will be blank at first)

**Comment by pstan26** [comment]
I think you have the priority right.

- Is the "to" field going to be a blockstack.id or a bitcoin wallet? (seeing blockstack.id in the example). Functionally, will this mean the user will have to exit this page to search or know off the top of their head which ID they will be sending to?


_----------------
ideas for distant future consideration: 
- [ ] `search user` by blockstack.id for both send and receive // or as a dropdown function when you click into `search` text field
- [ ] `address book` of personal contacts of blockstack.ids

---------------
not sure where to put this, but adding it here
- [ ] `send via email` upload email address book of your contacts into storage and send them an email allowing them to access funds by registering a name with blockstack_

**Comment by guylepage3** [comment]
complete
