### ISSUE TITLE
Unable to register a name in the portal

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#354]
I have $15 showing up in my wallet, but attempts to register a name are failing.

![screen shot 2017-03-24 at 2 13 15 pm](https://cloud.githubusercontent.com/assets/5605552/24309965/60330948-10a4-11e7-9bb3-c5bb3364ec47.png)
![screen shot 2017-03-24 at 2 13 25 pm](https://cloud.githubusercontent.com/assets/5605552/24309968/6037846e-10a4-11e7-8bf0-040141e50682.png)
![screen shot 2017-03-24 at 2 19 55 pm](https://cloud.githubusercontent.com/assets/5605552/24309966/6035a608-10a4-11e7-806d-ced951b987bc.png)
![screen shot 2017-03-24 at 2 21 50 pm](https://cloud.githubusercontent.com/assets/5605552/24309967/60363546-10a4-11e7-921a-6935d6db4513.png)

**Comment by shea256** [comment]
Looks like this is a duplicate to #353?

**Comment by pstan26** [comment]
yes looks like. closing
