### ISSUE TITLE
macOS: Integrate sparkle update framework

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#355]

**Comment by larrysalibra** [comment]
As part of this, I needed to update our build process to build a signed DMG #336.

**Comment by shea256** [comment]
Awesome, just took a look at this: https://sparkle-project.org/

**Comment by larrysalibra** [comment]
Successfully tested this after setting up a test appcast server. We'll need to set up one for production: #358 

On 1st run the user will see:
<img width="461" alt="screen shot 2017-03-26 at 5 25 41 pm" src="https://cloud.githubusercontent.com/assets/597182/24400655/cfd26e82-13e3-11e7-86a0-34e93b7df4ee.png">

On 2nd or later runs, the user will see the below dialog if there is an update.

<img width="624" alt="screen shot 2017-03-28 at 6 14 22 pm" src="https://cloud.githubusercontent.com/assets/597182/24400631/b68dfa72-13e3-11e7-948c-990b03cabc11.png">

**Comment by larrysalibra** [comment]
I configured the updater so that it doesn't prompt users about automatically checking for updates on 1st run. Better 1st run experience.

**Comment by larrysalibra** [comment]
The update process looks like this:

<img width="624" alt="screen shot 2017-03-28 at 6 14 22 pm" src="https://cloud.githubusercontent.com/assets/597182/24401688/ec15d9f4-13e7-11e7-920b-e8514e167f56.png">
<img width="409" alt="screen shot 2017-03-28 at 6 50 31 pm" src="https://cloud.githubusercontent.com/assets/597182/24401652/c786dd40-13e7-11e7-8e47-d3dba06ad94a.png">
<img width="410" alt="screen shot 2017-03-28 at 6 50 36 pm" src="https://cloud.githubusercontent.com/assets/597182/24401659/ccad3940-13e7-11e7-889c-d805dca2149b.png">

If the user opts in to automatic updates, the updates are silently downloaded in the background and installed when the user quits. We can enable this by default by setting this key:

<img width="1138" alt="screen shot 2017-03-28 at 6 54 54 pm" src="https://cloud.githubusercontent.com/assets/597182/24401720/15b8cfdc-13e8-11e7-82e0-93dcd094eee6.png">

**Comment by pstan26** [comment]
@larrysalibra @shea256 If it is true that **not** updating Blockstack will, in the immediate term, mean certain core things won't function at all -- then should we force automatic updates or change the wording to be more strongly encouraging automatic updating?

If the wording is too casual then the user will be confused when something major doesn't work. Right?
