### ISSUE TITLE
Design log aggregation & submission requirements with Core 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#376]
@jcnelson 
The Mac app expects log events to be `POST`ed to `http://localhost:8883`. It expects the same the `Authorization` header that Core expects from the Portal.

```JSON
{
"time": 1492012335558, 
"level": "TRACE", 
"category": "index.js", 
"message": "NODE_ENV is not production"
}
```
This is the code the Portal sends log events:
https://github.com/blockstack/blockstack-portal/blob/9b6f1771404f5a6a835da67bf3c8455897bd4c7b/app/js/utils/log4js/portal-appender.js#L8

`level` is one of these:

```JavaScript
const defaultLevels = {
    TRACE: new Level(5000, 'TRACE'),
    DEBUG: new Level(10000, 'DEBUG'),
    INFO: new Level(20000, 'INFO'),
    WARN: new Level(30000, 'WARN'),
    ERROR: new Level(40000, 'ERROR'),
    FATAL: new Level(50000, 'FATAL')
 }
```

This is how I map these levels to macOS`s logging system levels: https://github.com/blockstack/blockstack-portal/blob/9b6f1771404f5a6a835da67bf3c8455897bd4c7b/native/macos/Blockstack/Blockstack/PortalLogServer.swift#L136

`category` is a short identifier you think makes sense to group log messages by
`time` is unix time in milliseconds. The Mac app currently ignores this and uses the time it receives the message as the log time.

---

Can we add a command line option to provide the log server port on Core commands? If we don't provide a port, it could be off by default.

Let me know if you need any more information!

**Comment by jcnelson** [comment]
Pushed this to `rc-0.14.2` and `master-sprint-2017-04-13`

**Comment by larrysalibra** [comment]
@jcnelson thank you! I'll give a try ASAP.
