### ISSUE TITLE
get team to install sublime eslint plugin to auto-display lint errors

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-portal#380]
I'll ping @larrysalibra and @guylepage3 about this.

**Comment by larrysalibra** [comment]
I've installed the `linter-eslint` plugin in Atom.

**Comment by larrysalibra** [comment]
@shea256 what are your thoughts on `comma-dangle` http://eslint.org/docs/rules/comma-dangle?

**Comment by shea256** [comment]
@larrysalibra Traditionally I haven't used dangling commas but it does seem like a good practice as it leads to fewer mistakes with reordering items in lists. Airbnb supports dangling commas, which is why it's showing up as an error on our system. That said, I'm fine with either way.
