### ISSUE TITLE
Round up wallet amount

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#391]
![screen shot 2017-04-05 at 12 00 50 am](https://cloud.githubusercontent.com/assets/5605552/24689233/28f64cf4-1993-11e7-8ad6-108f1da70e11.png)

I don't think the last three digits are necessary on the bitcoin wallet, as they represent sub-penny value. It's one of weird quirks of cryptocurrency..that it is so easily divisible. The long string of digits also steals what would otherwise be regular spacing in the wallet.

Don't think this is a huge priority by any means, just something I noticed.

**Comment by guylepage3** [comment]
resolved

**Comment by guylepage3** [comment]
hm.. reopening this issue. @pstan26 has a good point. It's also a terrible ux to have so many decimal places.

+1

<img width="850" alt="screenshot 2017-04-17 16 48 17" src="https://cloud.githubusercontent.com/assets/1711854/25104329/d3467b80-238d-11e7-9a44-5326578e4d43.png">

**Comment by larrysalibra** [comment]
Rounded to 3 decimal places - hold mouseover for exact amount.

Great suggestion @pstan26 & @guylepage3
