### ISSUE TITLE
Twitter social proof not working

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-portal#397]
Filled out twitter username in portal and pushed button to "Create Tweet" but nothing happened.

![screen shot 2017-04-05 at 4 46 02 pm](https://cloud.githubusercontent.com/assets/5605552/24727360/b57a60f8-1a23-11e7-98fa-f7258f6b1303.png)
![screen shot 2017-04-05 at 5 15 29 pm](https://cloud.githubusercontent.com/assets/5605552/24727359/b5784c00-1a23-11e7-9750-3810dccf1a35.png)

**Comment by larrysalibra** [comment]
Thanks for the report! 

I didn't even know we had this feature! Will take a look at it.

**Comment by larrysalibra** [comment]
@pstan26 Fixed this in `v0.8`

Clicking the create tweet button should open a pre-filled tweet in a new tab:

<img width="1389" alt="screen shot 2017-05-01 at 12 50 38 pm" src="https://cloud.githubusercontent.com/assets/597182/25573161/dc48cc30-2e6c-11e7-870f-dccad206c81f.png">

Thank you again for reporting this!
