### ISSUE TITLE
Use proxy fetch for pgp keys

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#418]
We can't guarantee that's people's PGP keys are hosted on servers with proper CORS headers.

**Comment by larrysalibra** [comment]
I changed `proxyFetch` so that it always proxies. `fetch` will conditionally proxy URLs whose host names end in the value included in the list. `realFetch` never proxies. We should move away from overriding global `fetch`. I've opened an issue for that #448

@muneeb-ali our CORS proxy currently only supports `https` - the link to the PGP key in your profile doesn't use `https` (neither does mine! see @shea256 's for an example of a profile with a PGP key that works).

<img width="944" alt="screen shot 2017-05-01 at 1 50 24 pm" src="https://cloud.githubusercontent.com/assets/597182/25574089/25bd6dd2-2e75-11e7-8147-6f026b06eb96.png">

We don't need `https` for integrity since we have the fingerprint in the profile and can verify it. (we currently dont https://github.com/blockstack/blockstack-portal/issues/447).

We could add support to the CORS proxy for `http` at the cost of increased complexity:

I don't see this as a priority at the moment - especially since it would be great if all connections on the new internet that leave your device use encryption. Please open a new issue if you think we should support `http` in our CORS proxy and links in profiles.

**Comment by shea256** [comment]
+1 on moving away from overriding the real fetch. This is a good interim solution, though.

And yeah unfortunately if you're loading a PGP key over HTTP then you really shouldn't trust it. I agree that we should require HTTPS to load keys.

**Comment by vsund** [comment]
> And yeah unfortunately if you're loading a PGP key over HTTP then you really shouldn't trust it. I agree that we should require HTTPS to load keys.

But you actually don't need HTTPS for integrity reasons as @larrysalibra said. That's exactly the thing Blockstack solves :) You can load 3rd party key and look whether the fingerprint matches and thereby verify the key completely.

Data from keyservers (or other ressources) is not authenticated and never meant to be. The idea was that keys should get verified by participating in the Web of trust. This isn't needed anymore with using Blockstack (assuming you having already a name).

**Comment by larrysalibra** [comment]
@vsund You're right we don't need https for integrity. We do need HTTPS for privacy so that people watching that network don't know we're downloading PGP keys.
