### ISSUE TITLE
Separate repos for each app

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-portal#426]
This is more a question than an issue. Are there separate repos for each Blockstack "app" included with Portal? If not, why not? To me it makes the most sense that each app should be a separate project - Wallet, Profile, Storage, etc. Also brings to mind the question of app distribution. If I develop an app for Blockstack, how do users find it and add it to there Portal? Is the idea that there will be an app store or some other way of finding apps and adding them to your Portal? Or do all apps have to be added to the Portal repo and made available to all users at the same time?

**Comment by guylepage3** [comment]
@john-light I've posted your question [here](https://forum.blockstack.org/t/separate-repos-for-each-app/951) on the forum.
