### ISSUE TITLE
portal is launching locally on port 3000

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#429]
Portal is currently launching on port 3000 when it needs to be on 3001 or 3002

<img width="303" alt="screenshot 2017-04-19 18 12 44" src="https://cloud.githubusercontent.com/assets/1711854/25204548/f759db80-252b-11e7-9663-e376ae158798.png">

<img width="719" alt="screenshot 2017-04-19 18 14 33" src="https://cloud.githubusercontent.com/assets/1711854/25204565/0df19b9e-252c-11e7-9eb2-a622b0e7c0d3.png">

**Comment by larrysalibra** [comment]
@guylepage3 it's supposed to be port `3000` If you've already got something running on that port, it will run on `3001` and so forth. I've added ports `3000-3002` (inclusive) (along with`8888` for production) on our Dropbox app as valid redirect URLs.

**Comment by guylepage3** [comment]
@larrysalibra, hm.. i was unable to get the portal to run on my machine yesterday. thought it was due to port number. seems to be running fine now though.
