### ISSUE TITLE
many profiles give "zone file is missing an origin" error

### ISSUE THREAD

**Issue by dominictarr** [blockstack/blockstack-portal#461]
opening http://localhost:3000/profiles/shea256.id 
screen is mostly blank except for the search bar,
and I get this error in the console:

```
fetchCurrentIdentity: shea256.id resolveZoneFileToProfile: error zone file is missing an origin
```
I seem to see this on most profiles.

http://localhost:3000/profiles/larry.id is one that works.

**Comment by larrysalibra** [comment]
Thank you for reporting this @dominictarr 

Just pushed a fix!
