### ISSUE TITLE
live design of new profile completion screens

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#479]
Design a new home screen status bar

**Comment by guylepage3** [comment]
@shea256 just looking for all the possible items that could appear in the home screen status bar. Here's what i have so far;

- User's wallet balance
- Completion bar
- User's default profile image

**Comment by shea256** [comment]
- Default profile image
- Wallet balance
- Progress bar w/ to-do items
  - Create your keychain
  - Encrypt your keychain with a password
  - Backup your encrypted keychain with your email
  - Deposit bitcoin to register profiles
  - Create your first profile
  - Upload a profile image
  - Sign in to your first app

**Comment by guylepage3** [comment]
- Write down back-up phrase

**Comment by shea256** [comment]
New list:

- Set up your data storage
- Deposit bitcoin to register profiles
- Create your first profile
- Upload a profile image
- Sign in to your first app
- Write down back-up phrase

**Comment by shea256** [comment]
![2 1 tooltip](https://cloud.githubusercontent.com/assets/994646/26135841/361191c8-3a86-11e7-95a4-e9f5e8638eac.jpg)
![2 2 tooltip](https://cloud.githubusercontent.com/assets/994646/26135842/3611ec9a-3a86-11e7-9d7b-2a1e9effda9c.jpg)
![2 3 tooltip](https://cloud.githubusercontent.com/assets/994646/26135843/3613d67c-3a86-11e7-9015-7e99f2e27f56.jpg)

**Comment by shea256** [comment]
## 1.
![2 1 tooltip](https://cloud.githubusercontent.com/assets/994646/26136774/f0100456-3a8b-11e7-9d24-b0809905528b.jpg)

## 2.
![2 2 tooltip](https://cloud.githubusercontent.com/assets/994646/26136776/f012b156-3a8b-11e7-8163-f0632040ec18.jpg)

## 3.
![2 3 tooltip](https://cloud.githubusercontent.com/assets/994646/26136773/f00f9f20-3a8b-11e7-9b6c-75c644c9811d.jpg)

## 4.
![2 4 tooltip](https://cloud.githubusercontent.com/assets/994646/26136775/f00fef48-3a8b-11e7-926d-8ab6e9a003df.jpg)

## 5.
![2 5 tooltip](https://cloud.githubusercontent.com/assets/994646/26136777/f0142e1e-3a8b-11e7-8276-7575145e9aa5.jpg)

**Comment by guylepage3** [comment]
Nice! can you copy and paste the text in here for me for each screen? Thank you.

**Comment by guylepage3** [comment]
@shea256 @larrysalibra, shouldn't we just have one annoying red dot with one dropdown for user's to complete the process?

I usually skip over multiple dots or requirements as they don't annoy me. One red dot is an indicator that bothers me and i will do everything to get rid of it.

Thoughts?

**Comment by larrysalibra** [comment]
This is what I would do:

Have notification icon like facebook with a red dot or number, you when you click on it, you see these various tasks that need to be completed.

I'd also put red dots/numbers on the app icons in which we want the user to complete tasks. When they open the app, it goes to the page that allows them to complete the task and has a message/alert that tells them what they need to do.

**Comment by guylepage3** [comment]
>Have notification icon like facebook with a red dot or number, you when you click on it, you see these various tasks that need to be completed.

I would definitely like to see 1 red dot that is positioned in an annoying manner. this would be more of an annoyance that a long bar unless the bar was ugly. then i'd want to get rid of it.

i would also like to see one tooltip/dropdown appear every time the user opens blockstack. the user could simply click anywhere and the tooltip would disappear. so it's annoying but not too annoying that the user would never open blockstack again.

**Comment by guylepage3** [comment]
complete
