### ISSUE TITLE
redesign home screen

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#480]
Redesign the Portal Home Screen so that it is more neutral, modern and evokes a feeling that this could be the home screen for everyone on the new internet.

**Comment by guylepage3** [comment]
![portal-home-screen-01](https://cloud.githubusercontent.com/assets/1711854/26113791/8f37f876-3a29-11e7-932f-9a72f653e88e.png)

**Comment by guylepage3** [comment]
Another iteration
![portal-home-screen-01](https://cloud.githubusercontent.com/assets/1711854/26115865/41394f34-3a2f-11e7-990f-b5927efe9405.png)

**Comment by guylepage3** [comment]
![portal-home-screen-03](https://cloud.githubusercontent.com/assets/1711854/26117043/37763dbe-3a33-11e7-864c-e374b9aed854.png)

**Comment by guylepage3** [comment]
![portal-home-screen-04](https://cloud.githubusercontent.com/assets/1711854/26117173/953cb338-3a33-11e7-9357-2c46917b0808.png)

**Comment by guylepage3** [comment]
![portal-home-screen-05](https://cloud.githubusercontent.com/assets/1711854/26119899/f1deef6c-3a3c-11e7-92d6-aef8e400f1b9.png)

**Comment by guylepage3** [comment]
![portal-home-screen-07](https://cloud.githubusercontent.com/assets/1711854/26121273/b4a93a3a-3a41-11e7-8099-231879274d2f.png)

**Comment by guylepage3** [comment]
![portal-home-screen-08](https://cloud.githubusercontent.com/assets/1711854/26122388/4e1cbbb2-3a45-11e7-87bf-064491171f2e.png)

**Comment by shea256** [comment]
Nice! Responded to all of them.

**Comment by guylepage3** [comment]
Chosen v2 Home Screen design...

https://github.com/blockstack/blockstack-portal/issues/480#issuecomment-301868534
